import { Router } from 'express';

import healthRoutes from './health.routes';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import roleRoutes from './role.routes';
import locationRoutes from './location.routes';
import departmentRoutes from './department.routes';
import trainingTopicRoutes from './trainingTopic.routes';
import trainingMaterialRoutes from './trainingMaterial.routes';
import questionRoutes from './question.routes';
import scheduleRoutes from './schedule.routes';
import assignmentRoutes from './assignment.routes';
import attendanceRoutes from './attendance.routes';
import assessmentRoutes from './assessment.routes';
import certificateRoutes from './certificate.routes';
import jobDescriptionRoutes from './jobDescription.routes';
import personalDocumentRoutes from './personalDocument.routes';
import tniRoutes from './tni.routes';
import feedbackRoutes from './feedback.routes';
import announcementRoutes from './announcement.routes';
import eSignatureRoutes from './eSignature.routes';
import auditTrailRoutes from './auditTrail.routes';
import systemConfigRoutes from './systemConfig.routes';
import reportRoutes from './report.routes';
import dashboardRoutes from './dashboard.routes';
import adminRoutes from './admin.routes';
import certificateTemplateRoutes from './certificateTemplate.routes';
import integrationRoutes from './integration.routes';
import trainingTypeMasterRoutes from './trainingTypeMaster.routes';
import documentTypeMasterRoutes from './documentTypeMaster.routes';
import designationRoutes from './designation.routes';
import bundleRoutes from './bundle.routes';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/locations', locationRoutes);
router.use('/departments', departmentRoutes);
router.use('/topics', trainingTopicRoutes);
router.use('/materials', trainingMaterialRoutes);
router.use('/questions', questionRoutes);
router.use('/schedules', scheduleRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/assessments', assessmentRoutes);
router.use('/certificates', certificateRoutes);
router.use('/job-descriptions', jobDescriptionRoutes);
router.use('/personal-documents', personalDocumentRoutes);
router.use('/tni', tniRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/announcements', announcementRoutes);
router.use('/signatures', eSignatureRoutes);
router.use('/audit-trail', auditTrailRoutes);
router.use('/system-config', systemConfigRoutes);
router.use('/reports', reportRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/certificate-templates', certificateTemplateRoutes);
router.use('/integrations', integrationRoutes);
router.use('/master/training-types', trainingTypeMasterRoutes);
router.use('/master/document-types', documentTypeMasterRoutes);
router.use('/master/designations', designationRoutes);
router.use('/bundles', bundleRoutes);

export default router;
