export interface CsvColumn {
  header: string;
  key: string;
}

function escapeCsv(value: unknown): string {
  let s = value === null || value === undefined ? '' : String(value);
  // CSV formula-injection defence: a cell whose first character is = + - @ (or a
  // leading tab/CR) is evaluated as a formula by Excel/LibreOffice. Prefix such values
  // with an apostrophe so they are rendered as literal text, never executed.
  if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`;
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** Render columns + rows to a CSV string (RFC-4180 quoting), with a trailing
 *  "Generated by <user> on <date time>" footer line. */
export function exportToCsv(columns: CsvColumn[], rows: Array<Record<string, unknown>>, meta?: { generatedBy?: string }): string {
  const head = columns.map((c) => escapeCsv(c.header)).join(',');
  const body = rows.map((r) => columns.map((c) => escapeCsv(r[c.key])).join(',')).join('\r\n');
  const stamp = new Date().toLocaleString();
  const footer = meta?.generatedBy ? `Generated by ${meta.generatedBy} on ${stamp}` : `Generated on ${stamp}`;
  return `${head}\r\n${body}\r\n\r\n${escapeCsv(footer)}`;
}
