import ExcelJS from 'exceljs';

export interface ExcelColumn {
  header: string;
  key: string;
  width?: number;
}

/**
 * Excel sheet/tab names are limited by the .xlsx format to 31 characters and may not
 * contain \ / ? * [ ] : — sanitise and cap so any report title is a valid tab name.
 */
export function toSheetName(name: string): string {
  const cleaned = (name || 'Report').replace(/[\\/?*[\]:]/g, ' ').trim();
  return cleaned.slice(0, 31) || 'Report';
}

/**
 * Build an .xlsx Buffer from columns + rows (used by every report export). When
 * `titleRow` is supplied, the FULL title is written as a merged title row at the top of
 * the sheet (no length limit — unlike the 31-char tab name), so a long report/course
 * title is preserved in the exported content.
 */
export async function exportToExcel(
  columns: ExcelColumn[],
  rows: Array<Record<string, unknown>>,
  sheetName = 'Report',
  titleRow?: string,
  meta?: { generatedBy?: string },
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'izLearn';
  wb.created = new Date();
  const ws = wb.addWorksheet(toSheetName(sheetName));
  // Column widths (no auto-header — the header row is written explicitly below so it can
  // sit under an optional title row).
  columns.forEach((c, i) => {
    ws.getColumn(i + 1).width = c.width ?? 22;
  });

  if (titleRow && titleRow.trim()) {
    const tr = ws.addRow([titleRow]);
    if (columns.length > 1) ws.mergeCells(1, 1, 1, columns.length);
    tr.font = { bold: true, size: 14 };
    tr.alignment = { vertical: 'middle', wrapText: true };
  }

  const header = ws.addRow(columns.map((c) => c.header));
  header.font = { bold: true };
  header.alignment = { vertical: 'middle' };
  const headerRowNumber = header.number;

  rows.forEach((r) => ws.addRow(columns.map((c) => (r[c.key] ?? '') as ExcelJS.CellValue)));
  ws.autoFilter = { from: { row: headerRowNumber, column: 1 }, to: { row: headerRowNumber, column: columns.length } };

  // Footer: "Generated by <user> on <date time>" (a blank row keeps it clear of the data).
  ws.addRow([]);
  const stamp = new Date().toLocaleString();
  const footerText = meta?.generatedBy ? `Generated by ${meta.generatedBy} on ${stamp}` : `Generated on ${stamp}`;
  const fr = ws.addRow([footerText]);
  if (columns.length > 1) ws.mergeCells(fr.number, 1, fr.number, columns.length);
  fr.font = { italic: true, size: 9, color: { argb: 'FF94A3B8' } };

  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/**
 * Parse the first worksheet into row objects keyed by the header row. Each row
 * includes `__row` (1-based worksheet row number) for error reporting in
 * bulk-upload previews.
 */
export async function parseExcel(buffer: Buffer): Promise<Array<Record<string, unknown>>> {
  const wb = new ExcelJS.Workbook();
  // exceljs resolves `Buffer` from a transitively-bundled older @types/node,
  // which is structurally incompatible with the workspace's @types/node Buffer.
  // The cast bridges the two definitions for this otherwise valid runtime call.
  await wb.xlsx.load(buffer as unknown as Parameters<typeof wb.xlsx.load>[0]);
  const ws = wb.worksheets[0];
  if (!ws) return [];

  const headers: string[] = [];
  ws.getRow(1).eachCell((cell, col) => {
    headers[col] = String(cell.value ?? '').trim();
  });

  const rows: Array<Record<string, unknown>> = [];
  ws.eachRow((row, rowNumber) => {
    if (rowNumber === 1) return;
    const obj: Record<string, unknown> = { __row: rowNumber };
    row.eachCell((cell, col) => {
      const header = headers[col];
      if (header) {
        const v = cell.value as unknown;
        obj[header] =
          v && typeof v === 'object' && 'text' in (v as Record<string, unknown>)
            ? (v as { text: string }).text
            : v;
      }
    });
    rows.push(obj);
  });
  return rows;
}
