import { formatDateTime } from './dateUtils';

export interface ReportHeaderConfig {
  orgName: string;
  orgLogoPath?: string;
  reportTitle: string;
  referenceNumber: string;
  generatedByName: string;
  generatedByEmployeeId: string;
  generatedAt: Date;
  timezone?: string;
  /** When the document is being printed, include "Printed By/On". */
  printedByName?: string;
}

/**
 * Puppeteer header/footer templates. Puppeteer substitutes the special classes
 * `pageNumber` and `totalPages` at print time so every page shows "Page X of Y".
 * Used by every report and printed document (Module 11).
 */
export function buildHeaderTemplate(cfg: ReportHeaderConfig): string {
  const logo = cfg.orgLogoPath
    ? `<img src="${cfg.orgLogoPath}" style="height:28px;margin-right:10px;" />`
    : '';
  return `
  <div style="font-size:9px;width:100%;padding:4px 12px;border-bottom:1px solid #ccc;display:flex;align-items:center;justify-content:space-between;">
    <div style="display:flex;align-items:center;">${logo}<strong>${escapeHtml(cfg.orgName)}</strong></div>
    <div style="text-align:right;">
      <div><strong>${escapeHtml(cfg.reportTitle)}</strong></div>
      <div>Ref: ${escapeHtml(cfg.referenceNumber)}</div>
    </div>
  </div>`;
}

export function buildFooterTemplate(cfg: ReportHeaderConfig): string {
  const tz = cfg.timezone || 'UTC';
  const generated = formatDateTime(cfg.generatedAt, tz);
  const printedLine = cfg.printedByName
    ? `<span>Printed By: ${escapeHtml(cfg.printedByName)} &nbsp;|&nbsp; Printed: ${generated}</span>`
    : '';
  return `
  <div style="font-size:8px;width:100%;padding:4px 12px;border-top:1px solid #ccc;display:flex;justify-content:space-between;">
    <div>
      Generated By: ${escapeHtml(cfg.generatedByName)} (${escapeHtml(cfg.generatedByEmployeeId)}) &nbsp;|&nbsp;
      Generated: ${generated} &nbsp; ${printedLine}
    </div>
    <div>
      Page <span class="pageNumber"></span> of <span class="totalPages"></span> &nbsp;|&nbsp;
      Total Pages: <span class="totalPages"></span>
    </div>
  </div>`;
}

export function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
