import { useAuthStore } from '@/store/authStore';

/**
 * Lightweight client-side print helper. Opens a clean, self-contained document in
 * a new window and triggers the browser's print dialog (which can "print to PDF").
 * No server-side PDF dependency. The caller supplies a title and the body markup
 * (already-escaped/sanitised); a minimal print stylesheet is injected.
 */
export function printHtml(title: string, bodyHtml: string, meta?: { printedBy?: string }): void {
  const win = window.open('', '_blank', 'width=900,height=700');
  if (!win) return; // popup blocked — nothing we can do silently
  // Every printout/download carries a footer: "Generated by <user> on <date time>".
  // The name defaults to the logged-in user (read centrally here) so every caller gets
  // it without passing it explicitly; an explicit meta.printedBy overrides. The repeating
  // fixed footer reprints on each page; body has bottom padding so content never overlaps it.
  const stamp = new Date().toLocaleString();
  const who = meta?.printedBy ?? useAuthStore.getState().user?.fullName ?? '';
  const footer = who ? `Generated by ${escapeHtml(who)} on ${escapeHtml(stamp)}` : `Generated on ${escapeHtml(stamp)}`;
  win.document.write(`<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: Inter, system-ui, -apple-system, Segoe UI, Roboto, sans-serif; color: #1e293b; margin: 32px; padding-bottom: 40px; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  .sub { color: #64748b; font-size: 12px; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
  th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
  th { color: #475569; font-weight: 600; background: #f8fafc; }
  .section { font-size: 13px; font-weight: 600; color: #334155; margin: 18px 0 6px; text-transform: uppercase; letter-spacing: .03em; }
  .meta { font-size: 12px; color: #475569; }
  .print-foot { position: fixed; bottom: 0; left: 0; right: 0; background: #fff; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding: 4px 0; }
  @media print { body { margin: 0; padding-bottom: 28px; } @page { margin: 16mm; } }
</style>
</head>
<body>
<div class="print-foot">${footer}</div>
${bodyHtml}
<script>window.onload = function(){ window.focus(); window.print(); };</script>
</body>
</html>`);
  win.document.close();
}

/**
 * Open a server-rendered PDF blob in a new tab and trigger the browser's print dialog.
 * Unlike client-side printHtml, this keeps the server's audited "PRINT" event and the
 * "printed by" stamp baked into the PDF. Returns false if the pop-up was blocked so the
 * caller can surface a message. Used to make "Print" behave differently from "Download PDF".
 */
export function printPdfBlob(blob: Blob): boolean {
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (!win) {
    URL.revokeObjectURL(url);
    return false;
  }
  let printed = false;
  const trigger = () => {
    if (printed) return;
    printed = true;
    try {
      win.focus();
      win.print();
    } catch {
      /* the embedded PDF viewer provides its own print control */
    }
  };
  win.addEventListener('load', trigger);
  // Fallback: some browsers don't fire load for the embedded PDF viewer.
  setTimeout(trigger, 1500);
  setTimeout(() => URL.revokeObjectURL(url), 60000);
  return true;
}

/** Escape a string for safe insertion into the printable HTML. */
export function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Build a simple `<table>` from headers + rows for the printable view. */
export function printTable(headers: string[], rows: Array<Array<unknown>>): string {
  const head = headers.map((h) => `<th>${escapeHtml(h)}</th>`).join('');
  const body = rows
    .map((r) => `<tr>${r.map((c) => `<td>${escapeHtml(c)}</td>`).join('')}</tr>`)
    .join('');
  return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
}
